//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_mindsGarden : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 Movement
        {
            get
            {
                return SteamVR_Actions.mindsGarden_Movement;
            }
        }
        
        public virtual SteamVR_Action_Boolean Jump
        {
            get
            {
                return SteamVR_Actions.mindsGarden_Jump;
            }
        }
        
        public virtual SteamVR_Action_Boolean Settings
        {
            get
            {
                return SteamVR_Actions.mindsGarden_Settings;
            }
        }
        
        public virtual SteamVR_Action_Boolean Dash
        {
            get
            {
                return SteamVR_Actions.mindsGarden_Dash;
            }
        }
        
        public virtual SteamVR_Action_Boolean Screenshot
        {
            get
            {
                return SteamVR_Actions.mindsGarden_Screenshot;
            }
        }
        
        public virtual SteamVR_Action_Boolean triggerSelect
        {
            get
            {
                return SteamVR_Actions.mindsGarden_triggerSelect;
            }
        }
        
        public virtual SteamVR_Action_Boolean forward
        {
            get
            {
                return SteamVR_Actions.mindsGarden_forward;
            }
        }
        
        public virtual SteamVR_Action_Boolean left
        {
            get
            {
                return SteamVR_Actions.mindsGarden_left;
            }
        }
        
        public virtual SteamVR_Action_Boolean right
        {
            get
            {
                return SteamVR_Actions.mindsGarden_right;
            }
        }
        
        public virtual SteamVR_Action_Boolean back
        {
            get
            {
                return SteamVR_Actions.mindsGarden_back;
            }
        }
    }
}
